eclipse-pullpiri/pullpiri

Makefile
containers/Dockerfile-observer
containers/Dockerfile-player
containers/Dockerfile-server
doc/docs/developments.md
examples/README.md
examples/helloworld.sh
examples/resources/helloworld.yaml

add test method

---

doc/contribution/guidelines-en.md
doc/contribution/guidelines-kr.md

docs(guide): update md files

---

src/player/actioncontroller/src/grpc/sender.rs

issue : [TASK] Policy Checking
url : #27
desc : Implement Policy Checking func in ActionController Feature.
compile test Ok. unit test none.

Implement Policy Checking

---

src/player/filtergateway/src/filter/mod.rs
src/player/filtergateway/src/grpc/receiver.rs
src/player/filtergateway/src/manager.rs

[TASK] Filter Management Functionality
[#14](https://github.com/eclipse-pullpiri/pullpiri/issues/14)

feat(filter):[TASK] Filter Management Functionality

---

src/player/filtergateway/src/filter/mod.rs
src/player/filtergateway/src/manager.rs

added paused, resume function of filter
Closes #14 
Create filter
Remove filter
Pause filter
Resume filter

feat(filter):[TASK] Filter Management Functionality (additional fix)

---

src/player/actioncontroller/Cargo.toml
src/player/actioncontroller/src/runtime/bluechi/mod.rs

url : #26
desc : API Integration with bluechi about connect. compile test Ok. unit test none.

issue : [TASK] API Integration with Bluechi and NodeAgent

---

src/player/filtergateway/Cargo.toml
src/player/filtergateway/src/grpc/receiver.rs
src/player/filtergateway/src/manager.rs

Impl handle scenario
Closes #11

feat(grpc): feat(grpc):[TASK] Scenario Data Processing Functionality [#11]

---

src/player/Cargo.lock
src/player/actioncontroller/src/grpc/receiver.rs
src/player/actioncontroller/src/manager.rs
src/player/filtergateway/src/filter/mod.rs
src/player/filtergateway/src/grpc/receiver.rs
src/player/filtergateway/src/manager.rs
src/player/filtergateway/src/vehicle/dds/listener.rs
src/player/filtergateway/src/vehicle/dds/mod.rs
src/player/filtergateway/src/vehicle/mod.rs

related to #13 
and apply "cargo fmt"

action trigger on condition match

---

src/common/src/setting.rs
src/player/actioncontroller/Cargo.toml
src/player/actioncontroller/src/manager.rs
src/player/actioncontroller/src/runtime/bluechi/mod.rs
src/settings.yaml

add node type to settings.yaml

---

src/player/actioncontroller/src/grpc/mod.rs

url : #21
desc : Action controller grpc server open. compile test Ok. unit test none.

[TASK] Action Trigger Handling' #21

---

src/player/actioncontroller/src/runtime/bluechi/mod.rs

url : #50
desc : bug fix bluechi api. compile test Ok. unit test none.

[TASK] add bluechi node proxy for bug fix #50

---

src/player/actioncontroller/src/grpc/mod.rs
src/player/actioncontroller/src/grpc/receiver.rs
src/player/actioncontroller/src/grpc/sender.rs
src/player/actioncontroller/src/main.rs
src/player/actioncontroller/src/manager.rs
src/player/actioncontroller/src/runtime/bluechi/mod.rs
src/player/actioncontroller/src/runtime/mod.rs
src/player/actioncontroller/src/runtime/nodeagent/mod.rs

Unit Test Case For Module ActionController(Grpc,Bluechi,NodeAgent)
🔗 Related Issue
https://github.com/eclipse-pullpiri/pullpiri/issues/29
🧪 Test Method
Unit Test Cases For Each Component of Module ActionController(Grpc,Bluechi,NodeAgent)
✅ Checklist
[✅] Code conventions are followed
[✅] Tests are added/modified
[ X ] Documentation is updated (if necessary)
Label: status:in-progress

test(api): Unit Test Case For Module ActionController(Grpc,Bluechi,NodeAgent)[#29]

---

src/player/actioncontroller/src/grpc/mod.rs
src/player/actioncontroller/src/manager.rs

rm dup test code
fixed indent 
Closes #
build actioncontroller

bug: fixed build error

---

src/player/filtergateway/src/filter/mod.rs
src/player/filtergateway/src/grpc/sender.rs
src/player/filtergateway/src/manager.rs

Send gRpc message when meet condition
Closes #21 
run api-server, filtergateway, actioncontroller
subscribe topic 
send message of meet condition.

feat(grpc): trigger action when meet condtion

---

src/player/filtergateway/src/main.rs
src/player/filtergateway/src/manager.rs
src/player/filtergateway/src/vehicle/dds/mod.rs

reload scenario data from etcd when initializing time
Closes #18 
run etcd server
save the scenario using api-server to etcd
run filtergateway

feat(init): load all scenario on initialized

---

examples/resources/helloworld.yaml
src/player/actioncontroller/src/grpc/receiver.rs
src/player/filtergateway/src/manager.rs

url : #91
desc : modify filtergateway, yaml. compile test Ok. unit test OK.

[Task] Integration test. filtergateway, helloworld yaml. #91

---

src/player/actioncontroller/src/grpc/receiver.rs
src/player/actioncontroller/src/grpc/sender.rs
src/player/filtergateway/src/grpc/sender.rs
src/server/policymanager/src/grpc/receiver.rs

📝 PR Description
Modify ActionController(sender), policymanager(gRPC reciever) for proper error handling
🔗 Related Issue
Closes https://github.com/eclipse-pullpiri/pullpiri/issues/98
🧪 Test Method
sudo cargo test 
unit test ok
📸 Screenshots
✅ Checklist
[✅] Code conventions are followed
[✅] Tests are added/modified
[X] Documentation is updated (if necessary)

fix(api):Modify ActionController, policymanager(gRPC) for proper error handling[#98]

---

src/agent/Cargo.lock
src/agent/nodeagent/Cargo.toml
src/agent/nodeagent/src/grpc/mod.rs
src/agent/nodeagent/src/grpc/receiver.rs
src/agent/nodeagent/src/grpc/sender.rs
src/agent/nodeagent/src/main.rs
src/agent/nodeagent/src/manager.rs
src/common/Cargo.toml
src/common/src/etcd.rs
src/common/src/setting.rs
src/common/src/spec/artifact/mod.rs
src/common/src/spec/artifact/model.rs
src/common/src/spec/artifact/network.rs
src/common/src/spec/artifact/package.rs
src/common/src/spec/artifact/scenario.rs
src/common/src/spec/artifact/volume.rs
src/common/src/spec/k8s/pod.rs
src/common/src/spec/mod.rs
src/player/Cargo.lock
src/player/actioncontroller/Cargo.toml
src/player/actioncontroller/actioncontroller.md
src/player/filtergateway/Cargo.toml
src/player/vendor/lge_dds/Cargo.toml
src/server/Cargo.lock
src/server/apiserver/Cargo.toml
src/server/policymanager/src/grpc/receiver.rs
src/tools/Cargo.lock

security issue - upgrade tokio version
https://github.com/eclipse-pullpiri/pullpiri/issues/111
apply `cargo fmt`

RUSTSEC-2025-0023 and cargo fmt

---

.github/workflows/build-container.yml

feat(auth):Fix Dockerfile name in build-container.yml[#116]

feat(auth):Fix Dockerfile name in build-container.yml[#116]

---

src/agent/nodeagent/src/main.rs
src/agent/nodeagent/src/manager.rs
src/agent/nodeagent/src/resource/container.rs
src/agent/nodeagent/src/resource/mod.rs
src/common/proto/monitoringserver.proto
src/player/actioncontroller/src/manager.rs

- Updated `inspect` function to accept hostname as a parameter.
- Added detailed statistics collection for CPU, memory, and network usage.
- Modified `ContainerInfo` to include a new `stats` field for storing statistics.
- Refactored tests to accommodate changes in the `inspect` function.

Enhance container inspection by adding statistics retrieval (#193)

---

src/player/statemanager/src/grpc/receiver.rs
src/player/statemanager/src/main.rs
src/player/statemanager/src/manager.rs
src/player/statemanager/src/state_machine.rs

https://github.com/eclipse-pullpiri/pullpiri/actions/workflows/build.yml
Daily build is failed.
reason : During resolving conflict #213

[urgent] build error fix

---

doc/architecture/KR/3.LLD/StateManager_Model.md

[LLD] Add dev rules

---

.github/workflows/release.yml

📝 PR Description
feat(api)-Updating CD process for documentation badges[#289]
🔗 Related Issue
closes->
https://github.com/eclipse-pullpiri/pullpiri/issues/289
🧪 Test Method
In next Release we should able to see documentation badge.
✅ Checklist
[✅] Code conventions are followed
[✅] Tests are added/modified
[✅] Documentation is updated (if necessary)

feat(api)-Updating CD process for documentation badges[#289]

---

src/player/actioncontroller/src/grpc/receiver.rs
src/player/actioncontroller/src/manager.rs
src/player/filtergateway/src/filter/mod.rs
src/player/filtergateway/src/manager.rs
src/server/apiserver/src/artifact/mod.rs

Change Scenario State changing point

Implement scenario state management improvements
